### ISSUE TITLE
Adding access token to prevent spam

### ISSUE THREAD

**Issue by kinwahlai** [kayak/carthage_remote_cache#12]
Thank you for this tool. It is a good alternative to tmspzz/Rome.

I wonder if you will add the access token to the server and client to prevent spam because I have a plan to put it onto GCP

Example server will reject if access token is not matching

**Comment by juraj-blahunka** [comment]
Hi @kinwahlai thank you for the kind words!
Right now we don't plan on adding support for an access token as we deploy it on internal servers.
We will gladly accept a PR if you decide to add support for an access token.
