### ISSUE TITLE
Upload for platform

### ISSUE THREAD

**Issue by pjcau** [kayak/carthage_remote_cache#6]
HI, 

Thank to this utility because it's faster than Rome. I have some big depedency like Realm and some time go in broke pipe. So Do you can  download and upload for platform (iOS, macOS, watchOS, tvOS)?

thank you

**Comment by juraj-blahunka** [comment]
Hi @pjcau , thank you for the report, the changes (support for `--platform iOS,tvOS...` ) will be released in 0.0.10 shortly.

**Comment by pjcau** [comment]
thank you

**Comment by juraj-blahunka** [comment]
`0.0.10` was released which includes this feature work.
