### ISSUE TITLE
How to push a carthage dependency

### ISSUE THREAD

**Issue by pjcau** [kayak/carthage_remote_cache#9]
Hi, 

I have some framework that release a Carthage framework, also with other dependency, and I should to a pipeline in CI for each single frameworka nd in the end send to carthage_remote_cache the framework update. 

So you can possible to do this?

BR

J

**Comment by juraj-blahunka** [comment]
Hi @pjcau ,

carthage_remote_cache uploads all your frameworks which are listed in a `.version` file - this is created by `carthage` itself.

Have a look at `$ ls -la Carthage/Build/` - you will find all the dependencies from `Cartfile`.
Afterwards you can inspect the version file, e.g. `$ cat Carthage/Build/.sentry-cocoa.version`. The `"name": "Sentry"` will the the framework name, that carthage_remote_cache will upload.

**Comment by pjcau** [comment]
Yes, 

I see inside the  `$ ls -la Carthage/Build/`

```
drwxr-xr-x   9 jonny.cau  staff   288 Jun 21 12:44 .
drwxr-xr-x   4 jonny.cau  staff   128 Feb  1 15:23 ..
-rw-r--r--   1 jonny.cau  staff  1036 Jun 21 12:40 .Kingfisher.version
-rw-r--r--   1 jonny.cau  staff   810 Jun 21 12:41 .Reachability.swift.version
-rw-r--r--   1 jonny.cau  staff   340 Jun 21 12:44 .ddvideoplayer.version
drwxr-xr-x   6 jonny.cau  staff   192 Jun 21 12:41 Mac
drwxr-xr-x  19 jonny.cau  staff   608 Jun 21 12:44 iOS
drwxr-xr-x   8 jonny.cau  staff   256 Jun 21 12:41 tvOS
drwxr-xr-x   6 jonny.cau  staff   192 Jun 21 12:36 watchOS
```

bu when I use the command

`carthagerc upload -f -v`

I will see only two and not 3 dependency

`D, [2021-06-21T12:55:32.963770 #29222] DEBUG -- : Fetching server version from http://10.57.1.200:9292/version
D, [2021-06-21T12:55:32.975231 #29222] DEBUG -- : Will upload frameworks: ["Kingfisher", "Reachability"]
D, [2021-06-21T12:55:32.975777 #29222] DEBUG -- : Uploading .Kingfisher.version
D, [2021-06-21T12:55:32.975896 #29222] DEBUG -- : Uploading .Reachability.swift.version
D, [2021-06-21T12:55:32.984727 #29222] DEBUG -- : Archiving Kingfisher for iOS
D, [2021-06-21T12:55:32.988670 #29222] DEBUG -- : Archiving Reachability for iOS`

infact ddvideoplayer it's a framework created

**Comment by juraj-blahunka** [comment]
@pjcau could you please share the contents of `Cartfile`, `Cartfile.resolved` and `.ddvideoplayer.version`?

**Comment by pjcau** [comment]
Hi, 

so Cartfile is 

```
github "onevcat/Kingfisher"
github "ashleymills/Reachability.swift"
```

while the Cartfile.resolved is

`github "ashleymills/Reachability.swift" "v5.1.0"
github "onevcat/Kingfisher" "6.3.0"` 

in the end  .ddvideoplayer.version is 

```
{
  "Mac" : [

  ],
  "watchOS" : [

  ],
  "tvOS" : [

  ],
  "commitish" : "2.7.0",
  "iOS" : [
    {
      "hash" : "a272a7c3630eb47f1a03d1662cd3afab69ebb49c16f18ffc70ee9eb8c80aae01",
      "name" : "DDVideoPlayer",
      "linking" : "dynamic",
      "swiftToolchainVersion" : "5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)"
    }
  ]
}

```

**Comment by juraj-blahunka** [comment]
@pjcau You will need to list DDVideoPlayer in the `Cartfile`, then call `carthage update` and only then upload via carthage_remote_cache

**Comment by pjcau** [comment]
But this way it's very strange. DDVideoPlayer use only this Kingfisher and Reachability. So in the cartfile, I have to write only the depedency not also the new framework.

**Comment by juraj-blahunka** [comment]
I see. Right now carthage_remote_cache only supports upload/download for dependencies specified in `Cartfile`, it doesn't support upload for binaries which are built by current project.

As a workaround, you can create new consumer project of DDVideoPlayer and upload from that project.

**Comment by pjcau** [comment]
ok, I imagine it. So ca you put on road map this feature?

**Comment by juraj-blahunka** [comment]
I don't see this feature as something we would work on in the short term. However we do accept pull requests if you'd like to work on this yourself :)
